<div>

    @foreach ($posts as $item)
        <div class="flex md:flex-wrap flex-row md:pr-5 pr-0 mb-10  md:mx-0 mx-2">

            <div class="w-2/3 md:mx-0 mx-2 md:order-1 order-2">
                <span
                    class="text-xs text-gray-500 uppercase border-b-2 border-green-500">{{ $item['category_name'] }}</span>

                <h2
                    class="md:text-lg text-sm font-semibold text-gray-900 leading-tight mb-3 mt-1 md:line-clamp-3 line-clamp-2">
                    <a
                        href="{{ route('read', [$item['id'], Carbon\Carbon::parse($item['created_at'])->format('dmY'), $item['slug']]) }}">{{ $item['title'] }}</a>
                </h2>
                @if (!Agent::isMobile())
                    <p class="text-gray-600 text-sm line-clamp-2 sm:block hidden">{{ $item['description'] }}</p>
                @endif
                <div class="text-gray-700 mt-1">
                    <span class="text-xs">{{ Carbon\Carbon::parse($item['created_at'])->format('d M Y, H:m') }}
                        WIB</span>
                </div>
                <!-- most-recent-item-info -->
            </div>

            {{-- <img class="sm:w-1/3 h-auto md:h-44 sm:mt-0 mt-3 bg-gray-100 object-cover rounded overflow-hidden md:order-2 order-1"
                src="/storage/{{ $item['image']['media']['small'] ?? '' }}" alt="{{ $item['title'] }}"> --}}
            <img class="w-1/3 h-24 md:h-44 sm:mt-0 mt-3 bg-gray-100 object-cover rounded-lg overflow-hidden md:order-2 order-1"
                src="https://picsum.photos/seed/picsum/200/300">

        </div>
    @endforeach

    <div class="w-full flex flex-col items-stretch">
        <div wire:loading wire:target="loadMore" class="self-center my-10">
            <div class="animate-spin h-10 w-10">
            <?xml version="1.0" encoding="utf-8"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" style="margin-right:-2px;display:block;background-repeat-y:initial;background-repeat-x:initial;animation-play-state:paused" ><circle cx="50" cy="50" fill="none" stroke="#0b1d27" stroke-width="10" r="35" stroke-dasharray="164.93361431346415 56.97787143782138" transform="matrix(1,0,0,1,0,0)" style="transform:matrix(1, 0, 0, 1, 0, 0);animation-play-state:paused" ></circle><!-- generated by https://loading.io/ --></svg>
            </div>
        </div>

        @if (!$isEmpty)
        <button wire:click="loadMore" class="self-center px-4 py-2 rounded-md border border-gray-300 hover:bg-blue-600 hover:border-0 hover:text-white" type="button">
            Load More 
        </button>
        @endif
    </div>
</div>
