<div>
    <div class="container mx-auto">
        <div class="flex flex-wrap md:space-x-2 space-x-0">
            @foreach ($photos['hits'] as $item)
                <div class="lg:w-1/3 md:w-1/2 w-full">
                    <div class="flex-item border-0 border-gray-300 rounded-lg shadow-lg hover:shadow-xl transition-3 m-2 lg:ml-0">
                        <a href="{{ route('photo', [$item['id'], Carbon\Carbon::parse($item['created_at'])->format('dmY'), $item['slug']]) }}">
                            {{-- <img src="/storage/{{ $item['images'][0]['media']['cropped'] }}" alt="{{ $item['title'] }}"
                                class="object-cover w-full block" style="height: 180px"> --}}
                                <img src="https://placeimg.com/640/480/any" alt="{{ $item['title'] }}"
                                class="object-cover w-full block">
                        </a>
                        <h2 class="text-gray-800 font-semibold text-base leading-tight p-3 pb-0 line-clamp-2"> <a
                                href="{{ route('photo', [$item['id'], Carbon\Carbon::parse($item['created_at'])->format('dmY'), $item['slug']]) }}">
                                {{ $item['title'] }} </a></h2>
                        <div class="w-full text-xs p-3 pt-2">
                            {{-- <div class="text-gray-600"> <a href="author.html" class="text-black hover:underline">Neelam
                                    Munir</a> in <a href="category-page.html" class="text-black hover:underline">
                                    Culture
                                </a> </div> --}}
                            <div class="text-gray-600"> <span>{{ Carbon\Carbon::parse($item['created_at'])->format('d M Y, H:m') }} WIB</span> </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>

    <div class="w-full flex flex-col items-stretch">
        <div wire:loading wire:target="loadMorePhoto" class="self-center my-10">
            <div class="animate-spin h-10 w-10">
            <?xml version="1.0" encoding="utf-8"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" style="margin-right:-2px;display:block;background-repeat-y:initial;background-repeat-x:initial;animation-play-state:paused" ><circle cx="50" cy="50" fill="none" stroke="#0b1d27" stroke-width="10" r="35" stroke-dasharray="164.93361431346415 56.97787143782138" transform="matrix(1,0,0,1,0,0)" style="transform:matrix(1, 0, 0, 1, 0, 0);animation-play-state:paused" ></circle><!-- generated by https://loading.io/ --></svg>
            </div>
        </div>

        @if (!$isEmpty)
        <button wire:click="loadMorePhoto" class="self-center px-4 py-2 rounded-md border border-gray-300 hover:bg-blue-600 hover:border-0 hover:text-white" type="button">
            Load More 
        </button>
        @endif
    </div>

</div>